spring.application.name=cbpOrderService


server.port=9092
server.servlet.contex-path=/home
springdoc.api-docs.path=/api
## Server connections configuration
server.max-http-header-size=64kb
#Postgres db configuration.
server.max-http-request-header-size=240004KB


spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.schema=classpath:/schema.sql
spring.datasource.continue-on-error=true
#
#
#
spring.datasource.url=jdbc:postgresql://localhost:5432/db1
spring.datasource.username=postgres
spring.datasource.password=bhashker








