spring.application.name=customActuatorService


server.port=8084
server.servlet.context-path=/customActuatorService
#springdoc.api-docs.path=/api
## Server connections configuration
#server.max-http-header-size=64kb
#Postgres db configuration.
#server.max-http-request-header-size=240004KB


spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.schema=classpath:/schema.sql
spring.datasource.continue-on-error=true
#
#
#
spring.datasource.url=jdbc:postgresql://localhost:5432/db1
spring.datasource.username=postgres
spring.datasource.password=bhashker

#Actuator configuration.
management.endpoints.web.base-path=/details
#change the default endpoint of actuator
## By default, all IDs are set to false except for ‘health’. To include an ID, use the following property
#management.endpoint.<id>.enabled
management.endpoint.metrics.enabled=true
#List down all IDs that you want to include which are separated by a comma
#management.endpoints.web.exposure.include=info,metrics
#To add/include all ID information about your application, you can do it in the application.properties file by simply adding the following
management.endpoints.web.exposure.include=*

#Excluding IDs/Endpoints
##management.endpoints.web.exposure.exclude=beans



